// 此文件由 scripts/generate-contracts.py 生成，请勿手改。
pub(crate) const AGENT_IDS: &[&str] = &["claude", "codex", "opencode", "pi", "grok", "cursor"];
pub(crate) const AGENT_CAPABILITIES: &[(&str, &[&str])] = &[
    (
        "claude",
        &[
            "browse",
            "resume",
            "migration-source",
            "migration-target",
            "edit",
            "delete",
            "probe",
            "prompt",
            "models",
        ],
    ),
    (
        "codex",
        &[
            "browse",
            "resume",
            "migration-source",
            "migration-target",
            "edit",
            "delete",
            "probe",
            "prompt",
            "models",
        ],
    ),
    (
        "opencode",
        &[
            "browse",
            "resume",
            "migration-source",
            "migration-target",
            "edit",
            "delete",
            "probe",
            "prompt",
            "models",
        ],
    ),
    (
        "pi",
        &[
            "browse",
            "resume",
            "migration-source",
            "migration-target",
            "edit",
            "delete",
            "probe",
            "prompt",
            "models",
        ],
    ),
    (
        "grok",
        &[
            "browse",
            "resume",
            "migration-source",
            "migration-target",
            "delete",
            "probe",
            "prompt",
            "models",
        ],
    ),
    ("cursor", &["browse", "migration-source"]),
];
pub(crate) const ALLOWED_EXECUTABLES: &[&str] =
    &["claude", "codex", "opencode", "pi", "grok", "cursor"];
