// 此文件由 scripts/generate-contracts.py 生成，请勿手改。
const PUBLIC_RUNTIME_METHODS: &[&str] = &[
    "health",
    "session.create",
    "session.rename",
    "session.pin",
    "session.delete",
    "roles.list",
    "role.create",
    "role.update",
    "role.copy",
    "role.delete",
    "organization.start",
    "prompt",
    "abort",
    "steer",
    "follow_up",
    "state",
    "sessions.list",
    "events.replay",
    "providers.list",
    "provider.enabled.set",
    "provider.test",
    "models.list",
    "models.enabled",
    "models.catalog",
    "custom_model.add",
    "custom_model.delete",
    "models.visibility.set",
    "models.refresh",
    "config.get",
    "credential.set",
    "provider.logout",
    "model.select",
    "custom_provider.upsert",
    "custom_provider.delete",
    "auth.login.start",
    "auth.login.respond",
    "auth.login.cancel",
];

pub(crate) fn is_public(method: &str) -> bool {
    PUBLIC_RUNTIME_METHODS.contains(&method)
}
