// 全局弹层的输入组装。哪些弹层存在、各自需要什么,集中在这里声明,
// 主壳只负责把结果转交给 AppOverlayController;新增弹层不必改动渲染骨架。
export function buildOverlayProps({
  setView,
  environment: env,
  settings,
  setSettings,
  settingsOpen,
  setSettingsOpen,
  settingsSection,
  updater,
  onboarding,
  rail,
  railOnly,
  scan,
  scanning,
  scanProgress,
  doScan,
  toast,
  setToast,
}) {
  return {
    toast: { value: toast, setValue: setToast },
    railTip: { value: rail.railTip, railOnly },
    settings: {
      open: settingsOpen,
      value: settings,
      onChange: setSettings,
      updater,
      section: settingsSection,
      scanResult: scan,
      env,
      scanning,
      scanProgress,
      scan: doScan,
      guideSeen: onboarding.seen,
      setOpen: setSettingsOpen,
      openGuide: onboarding.openGuide,
      setView,
    },
    guide: {
      step: onboarding.step,
      onGo: onboarding.setStep,
      onFinish: onboarding.finishGuide,
    },
  };
}
