// 全局弹层的输入组装。哪些弹层存在、各自需要什么,集中在这里声明,
// 主壳只负责把结果转交给 AppOverlayController;新增弹层不必改动渲染骨架。
export function buildOverlayProps({
  // 工作区与导航
  view,
  setView,
  environment: env,
  settings,
  setSettings,
  settingsOpen,
  setSettingsOpen,
  settingsSection,
  updater,
  onboarding,
  rail,
  railOnly,
  // 会话与详情
  sessions,
  current,
  selectedId,
  detail,
  detailMeta,
  detailActions,
  refreshing,
  loadingMore,
  navigationTarget,
  scan,
  scanning,
  doScan,
  // 编辑
  dirtyOps,
  diff,
  setDiff,
  confirmApply,
  setConfirmApply,
  applyEdit,
  // 元数据
  metaFor,
  updateMetadata,
  reloadMetadata,
  // 弹层各自的开关与选中
  organizerOpen,
  setOrganizerOpen,
  peekId,
  setPeekId,
  migration,
  setMigration,
  loadHistory,
  searchOpen,
  setSearchOpen,
  paneConfig,
  ferrySessions,
  libraryGroups,
  historyGroups,
  selectHistory,
  select,
  setMultiIds,
  menu,
  menuItems,
  setMenu,
  deletion,
  historyDeletion,
  setHistoryDeletion,
  deleteHistory,
  selectedHistoryId,
  rename,
  setRename,
  agentRename,
  setAgentRename,
  tagSelection,
  setTagSelection,
  toast,
  setToast,
  popover,
  popoverAnchor,
  setPopover,
  libraryFilter,
  setLibraryFilter,
  libraryCounts,
  libraryDirs,
  libraryTags,
  clearLibraryFilter,
  historyFilter,
  setHistoryFilter,
  clearHistoryFilter,
}) {
  return {
    organization: {
      open: organizerOpen,
      sessions,
      setOpen: setOrganizerOpen,
      reloadMetadata,
      scan: doScan,
    },
    peek: {
      id: peekId,
      current,
      selectedId,
      meta: detailMeta,
      detail,
      actions: detailActions,
      navigationTarget,
      refreshing,
      loadingMore,
      setId: setPeekId,
      setView,
    },
    migration: {
      state: migration,
      current,
      env,
      settings,
      setState: setMigration,
      loadHistory,
    },
    editing: {
      diff,
      dirtyOps,
      confirmApply,
      setDiff,
      setConfirmApply,
      apply: applyEdit,
    },
    search: {
      open: searchOpen,
      pane: paneConfig,
      view,
      ferrySessions,
      historyGroups,
      libraryGroups,
      selectHistory,
      setMultiSelection: setMultiIds,
      selectSession: select,
      setOpen: setSearchOpen,
    },
    contextMenu: {
      value: menu,
      items: menuItems,
      setValue: setMenu,
    },
    deletion: {
      sessionConfirmation: deletion.sessionConfirmation,
      batchConfirmation: deletion.batchConfirmation,
      cancelSessionDeletion: deletion.cancelSessionDeletion,
      confirmSessionDeletion: deletion.confirmSessionDeletion,
      cancelBatchDeletion: deletion.cancelBatchDeletion,
      confirmBatchDeletion: deletion.confirmBatchDeletion,
      history: historyDeletion,
      setHistory: setHistoryDeletion,
      deleteHistory,
      selectedHistoryId,
      selectHistory,
    },
    rename: {
      session: rename,
      setSession: setRename,
      metaFor,
      updateMetadata,
    },
    agentRename: {
      session: agentRename,
      setSession: setAgentRename,
    },
    tags: {
      selection: tagSelection,
      setSelection: setTagSelection,
      metaFor,
      updateMetadata,
    },
    toast: { value: toast, setValue: setToast },
    railTip: { value: rail.railTip, railOnly },
    settings: {
      open: settingsOpen,
      value: settings,
      onChange: setSettings,
      updater,
      section: settingsSection,
      scanResult: scan,
      env,
      scanning,
      scan: doScan,
      guideSeen: onboarding.seen,
      setOpen: setSettingsOpen,
      openGuide: onboarding.openGuide,
      setView,
    },
    filters: {
      popover,
      anchor: popoverAnchor,
      onClose: () => setPopover(null),
      library: {
        value: libraryFilter,
        onChange: setLibraryFilter,
        counts: libraryCounts,
        dirs: libraryDirs,
        tags: libraryTags,
        onClear: clearLibraryFilter,
      },
      history: {
        value: historyFilter,
        onChange: setHistoryFilter,
        onClear: clearHistoryFilter,
      },
    },
    guide: {
      step: onboarding.step,
      onGo: onboarding.setStep,
      onFinish: onboarding.finishGuide,
    },
  };
}
