// 此文件由 scripts/generate-contracts.py 生成，请勿手改。

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ErrorPolicy {
    pub category: &'static str,
    pub retryable: bool,
    pub sources: &'static [&'static str],
}

/// 契约里注册的全部错误码（字典序）。
pub const FERRY_ERROR_CODES: &[&str] = &[
    "agent.approval_invalid",
    "agent.format_changed",
    "agent.reference_invalid",
    "agent.request_invalid",
    "agent.run_missing",
    "already_restored",
    "auth_in_progress",
    "auth_login_not_found",
    "auth_prompt_not_found",
    "auth_type_unsupported",
    "choice.invalid_answer",
    "choice.request_closed",
    "choice.request_id_in_use",
    "choice.request_not_found",
    "edit.invalid_reply",
    "edit.operation_unsupported",
    "edit.subagent_not_supported",
    "edit.turn_out_of_range",
    "engine.invalid_response",
    "engine.request_failed",
    "engine.timeout",
    "engine.unavailable",
    "internal.unexpected",
    "internal_error",
    "invalid_json",
    "invalid_params",
    "invalid_provider_config",
    "invalid_request",
    "invalid_role",
    "invalid_skill",
    "model_capability_mismatch",
    "model_not_found",
    "no_active_run",
    "operation.invalid_status",
    "operation.unknown_status",
    "provider_in_use",
    "provider_not_found",
    "provider_unavailable",
    "provider_unreachable",
    "role_not_found",
    "rpc.invalid_json",
    "rpc.invalid_request",
    "rpc.missing_param",
    "rpc.unknown_method",
    "rpc.unsupported_protocol",
    "run_in_progress",
    "session.asset_not_found",
    "session.concurrent_modification",
    "session.locator_stale",
    "session.not_found",
    "session.store_unavailable",
    "session_exists",
    "session_not_found",
    "skill_not_found",
    "tool.invalid_args",
    "tool.not_allowed",
    "tool.unknown",
    "unknown_method",
    "unknown_tool_request",
    "unsupported",
    "unsupported_protocol",
];

pub fn error_policy(code: &str) -> Option<ErrorPolicy> {
    match code {
        "agent.approval_invalid" => Some(ErrorPolicy {
            category: "permission",
            retryable: false,
            sources: &["host"],
        }),
        "agent.format_changed" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["engine"],
        }),
        "agent.reference_invalid" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "agent.request_invalid" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "agent.run_missing" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["host"],
        }),
        "already_restored" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "auth_in_progress" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "auth_login_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "auth_prompt_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "auth_type_unsupported" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["runtime"],
        }),
        "choice.invalid_answer" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["host"],
        }),
        "choice.request_closed" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["host"],
        }),
        "choice.request_id_in_use" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["host"],
        }),
        "choice.request_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["host"],
        }),
        "edit.invalid_reply" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "edit.operation_unsupported" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["engine"],
        }),
        "edit.subagent_not_supported" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["engine"],
        }),
        "edit.turn_out_of_range" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "engine.invalid_response" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["host"],
        }),
        "engine.request_failed" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["host"],
        }),
        "engine.timeout" => Some(ErrorPolicy {
            category: "unavailable",
            retryable: true,
            sources: &["host"],
        }),
        "engine.unavailable" => Some(ErrorPolicy {
            category: "unavailable",
            retryable: true,
            sources: &["host"],
        }),
        "internal.unexpected" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["engine"],
        }),
        "internal_error" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_json" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_params" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_provider_config" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_request" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_role" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "invalid_skill" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "model_capability_mismatch" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["runtime"],
        }),
        "model_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "no_active_run" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "operation.invalid_status" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["host"],
        }),
        "operation.unknown_status" => Some(ErrorPolicy {
            category: "internal",
            retryable: false,
            sources: &["host"],
        }),
        "provider_in_use" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "provider_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "provider_unavailable" => Some(ErrorPolicy {
            category: "unavailable",
            retryable: true,
            sources: &["runtime"],
        }),
        "provider_unreachable" => Some(ErrorPolicy {
            category: "unavailable",
            retryable: true,
            sources: &["runtime"],
        }),
        "role_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "rpc.invalid_json" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "rpc.invalid_request" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "rpc.missing_param" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "rpc.unknown_method" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["engine"],
        }),
        "rpc.unsupported_protocol" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["engine"],
        }),
        "run_in_progress" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "session.asset_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["engine"],
        }),
        "session.concurrent_modification" => Some(ErrorPolicy {
            category: "conflict",
            retryable: true,
            sources: &["engine"],
        }),
        "session.locator_stale" => Some(ErrorPolicy {
            category: "conflict",
            retryable: true,
            sources: &["engine"],
        }),
        "session.not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["engine"],
        }),
        "session.store_unavailable" => Some(ErrorPolicy {
            category: "unavailable",
            retryable: true,
            sources: &["engine"],
        }),
        "session_exists" => Some(ErrorPolicy {
            category: "conflict",
            retryable: false,
            sources: &["runtime"],
        }),
        "session_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "skill_not_found" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "tool.invalid_args" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["host"],
        }),
        "tool.not_allowed" => Some(ErrorPolicy {
            category: "permission",
            retryable: false,
            sources: &["host"],
        }),
        "tool.unknown" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["engine"],
        }),
        "unknown_method" => Some(ErrorPolicy {
            category: "validation",
            retryable: false,
            sources: &["runtime"],
        }),
        "unknown_tool_request" => Some(ErrorPolicy {
            category: "not-found",
            retryable: false,
            sources: &["runtime"],
        }),
        "unsupported" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["runtime"],
        }),
        "unsupported_protocol" => Some(ErrorPolicy {
            category: "unsupported",
            retryable: false,
            sources: &["runtime"],
        }),
        _ => None,
    }
}
